---
title: "CrimeVsWeather"
author: "Tre Butler"
date: "4/22/2020"
output: html_notebook
---

```{r}
## Set Up

#install.packages(c("cowplot", "googleway", "ggplot2", "ggrepel", 
#"ggspatial", "libwgeom", "sf", "rnaturalearth", "rnaturalearthdata", 
#"rworldxtra","ggmap","digest","glue","cowplot"))
```
```{r}
#install.packages()
```
```{r warning=TRUE}
# clean up workspace environment
rm(list = ls())

# all packages used for the assignment
library(mosaicData)
library(mosaic)
library(DataComputing)
library(tidyverse)
library(forcats)
library(lubridate)
library(readxl)
library(ggplot2)
theme_set(theme_bw())
library(sp)
library(rworldmap)
library(leaflet)
library(data.table)
library(rgdal)
library(KernSmooth)
library(raster)
```

```{r message=FALSE, warning=FALSE}
#creating the datasets
boston_crime_statistics <- read_excel("crime.xlsx")
weather_data <- read_csv("weather data.csv")
weather_data <- weather_data%>%
  dplyr::select(NAME,LATITUDE,LONGITUDE,DATE,PRCP, TAVG,SNOW)
```

## Joining datasets to create CrimeVsWeather Table
```{r}
CrimeVsWeather <-
  boston_crime_statistics %>%
  mutate("DATE" = ymd(as.Date(OCCURRED_ON_DATE))) %>%
  left_join(weather_data,"DATE")
```

## Using date verbs to create data for our graphic
```{r}
CrimeVsWeather <- 
  CrimeVsWeather %>%
  group_by(TAVG) %>%
  summarise(Total = n()) %>%
  arrange(desc(Total))
CrimeVsWeather
```

## Bar Graph Showing Avg Temperature Vs Crimes Committed
```{r}
CrimeVsWeather %>% 
  ggplot(aes(x=TAVG,y=Total )) +
  geom_bar(stat='identity',position='stack', width=.9) 
```

