---
title: "Final Project" 
author: "Philip Saroka"
output: html_notebook
---

```{r}
# clean up workspace environment
rm(list = ls())

# all packages used for the assignment
library(mosaicData)
library(mosaic)
library(DataComputing)
library(tidyverse)
library(forcats)
library(lubridate)
library(readxl)
```

```{r}
#creating the datasets
boston_crime_statistics <- read_excel("crime.xlsx")
weather_data <- read_csv("weather data.csv")
weather_data <- weather_data%>%
  select(NAME,LATITUDE,LONGITUDE,DATE,PRCP, TAVG,SNOW)
```

```{r}
boston_crime_statistics
weather_data
```

```{r}
date_of_incident <- boston_crime_statistics%>%
  select(INCIDENT_NUMBER,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR)%>%
  arrange(OCCURRED_ON_DATE)
loaction_of_incident <- boston_crime_statistics%>%
  select(INCIDENT_NUMBER,OCCURRED_ON_DATE,UCR_PART,STREET,Lat,Long, Location)%>%
  arrange(OCCURRED_ON_DATE)
```

```{r}
date_of_incident
loaction_of_incident
```

```{r}

boston_crime_statistics%>%
  select(OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR)%>%
  arrange(OCCURRED_ON_DATE)%>%
  head(10)

boston_crime_statistics%>%
  select(OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR)%>%
  arrange(OCCURRED_ON_DATE)%>%
  tail(10)
```
```{r}
small_data <- boston_crime_statistics%>%
  group_by(OFFENSE_CODE)%>%
  summarise(total = n())
```
```{r}
ggplot(data=small_data,aes(x=OFFENSE_CODE,y=total))+geom_point()
```

